api_platform:
    # The title of the API.
    title: 'apilisin api'

    # The description of the API.
    description: 'apilisin api'

    # The version of the API.
    version: '0.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
