api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login_check
    methods: POST

register:
    path: /api/register
    defaults: { _controller: 'App\Controller\Api\RegistrationController:registerAction' }
    methods: POST