api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login_check
    defaults: { _controller: 'App\Controller\Api\SecurityController::loginCheckAction' }
    methods: POST
