homepage:
    path: /
    defaults: { _controller: 'App\Controller\Web\DefaultController::indexAction' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\Web\SecurityController::loginAction' }
