homepage:
    path: /
    defaults: { _controller: 'App\Controller\Web\DefaultController::index' }

register:
    path: /register
    defaults: { _controller: 'App\Controller\Web\RegistrationController:register' }